# ==================================================
# ServerBridge Configuration
# ==================================================

webhook:
  # Enable or disable outbound webhook events.
  enabled: false

  # Endpoint that receives POST requests.
  url: ""

  # HTTP request timeout in seconds.
  timeout: 5

  events:
      player.join:
        enabled: true
        message: "🟢 {player} joined the server!"
    
      player.first_join:
        enabled: true
        message: "🎉 {player}! This is their first join!"
    
      player.leave:
        enabled: true
        message: "🔴 {player} left the server!"